@host = http://localhost:5010

POST {{host}}/api/auth/register
Content-Type: application/json

{
  "firstName": "Salani",
  "middleName": "Kum",
  "lastName": "Salam",
  "gender": "Male", 
  "email": "salam23@gmail.com", 
  "mobileNumber": "09123456789",
  "address": "240 Rizal Avenue",
  "birthday": "2000-01-01",
  "username": "salani123",
  "password": "Passw0rd!",
  "confirmPassword": "Passw0rd!"
}


POST {{host}}/api/auth/login
Content-Type: application/json

{ "username": "salani123", "password": "Passw0rd!" }

@token = PASTE_TOKEN_HERE
GET {{host}}/api/passengers/1
Authorization: Bearer {{token}}

PUT {{host}}/api/passengers/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "email": "salam23@gmail.com",
  "mobileNumber": "09123456789",
  "address": "240 Rizal Avenue",
  "currentPassword": "Passw0rd!",
  "password": "NewPassw0rd!", 
  "confirmPassword": "NewPassw0rd!"
}

GET {{host}}/api/passengers/1

GET {{host}}/api/passengers/check-username?value=salani123
